version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: documentation
    versions:
    - 13.1.0
    - 13.1.1
    - 13.2.0
    - 13.2.1
    - 13.2.4
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: husky
    versions:
    - 4.3.6
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  registries:
  - npm-registry-npm-pkg-github-com
  - git-github-com
